services:
  app:
    build: .
    container_name: portfolio-app
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      # SESSION_SECRET: your-secret-key
    ports:
      - "5000:5000"
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
